<a href="https://colab.research.google.com/github/robbytbg/classWork/blob/main/lab1_BDO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
install.packages("pracma", reinstall = TRUE)


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [ ]:
# Set seed for reproducibility
set.seed(123)

# Create two matrices
even_matrix <- matrix(sample(2:20, 9, replace = FALSE), nrow = 3)
odd_matrix <- matrix(sample(1:19, 9, replace = FALSE), nrow = 3)

# Print the matrices
cat("Even Matrix:\n")
print(even_matrix)

cat("\nOdd Matrix:\n")
print(odd_matrix)

# Matrix addition
addition_matrix <- even_matrix + odd_matrix

# Print the addition matrix
cat("\nAddition Matrix:\n")
print(addition_matrix)

# Matrix subtraction
subtraction_matrix <- even_matrix - odd_matrix

# Print the subtraction matrix
cat("\nSubtraction Matrix:\n")
print(subtraction_matrix)

# Matrix multiplication
multiplication_matrix <- even_matrix %*% odd_matrix

# Print the multiplication matrix
cat("\nMultiplication Matrix:\n")
print(multiplication_matrix)

# Transpose of matrices
even_transpose <- t(even_matrix)
odd_transpose <- t(odd_matrix)

# Print the transposed matrices
cat("\nEven Transpose:\n")
print(even_transpose)

cat("\nOdd Transpose:\n")
print(odd_transpose)

# Check determinant
library(pracma)  # Use pracma package instead of MASS

even_det <- det(even_matrix)
odd_det <- det(odd_matrix)

# Print the determinants
cat("\nDeterminant of Even Matrix:", even_det)
cat("\nDeterminant of Odd Matrix:", odd_det)

# Check for inverses
# Print matrix inverses

if (even_det != 0) {
  even_inverse <- solve(even_matrix)
  cat("\nInverse of Even Matrix:\n")
  print(even_inverse)
} else {
  cat("\nEven matrix has no inverse as its determinant is zero.")
}

if (odd_det != 0) {
  odd_inverse <- solve(odd_matrix)  # Use solve function for potentially invertible odd matrix
  cat("\nInverse of Odd Matrix:\n")
  print(odd_inverse)
} else {
  # If determinant is zero, check for generalized inverse using other packages
  if (require(matrixcalc)) {
    odd_inverse <- ginv(odd_matrix)
    cat("\nGeneralized Inverse of Odd Matrix:\n")
    print(odd_inverse)
  } else {
    cat("\nOdd matrix has no inverse (or generalized inverse) as its determinant is zero.")
  }
}



Even Matrix:
     [,1] [,2] [,3]
[1,]   16   11   12
[2,]   15    3    6
[3,]    4    7    5

Odd Matrix:
     [,1] [,2] [,3]
[1,]   14   13   10
[2,]    5    3    7
[3,]    9    8   16

Addition Matrix:
     [,1] [,2] [,3]
[1,]   30   24   22
[2,]   20    6   13
[3,]   13   15   21

Subtraction Matrix:
     [,1] [,2] [,3]
[1,]    2   -2    2
[2,]   10    0   -1
[3,]   -5   -1  -11

Multiplication Matrix:
     [,1] [,2] [,3]
[1,]  387  337  429
[2,]  279  252  267
[3,]  136  113  169

Even Transpose:
     [,1] [,2] [,3]
[1,]   16   15    4
[2,]   11    3    7
[3,]   12    6    5

Odd Transpose:
     [,1] [,2] [,3]
[1,]   14    5    9
[2,]   13    3    8
[3,]   10    7   16

Determinant of Even Matrix: 123
Determinant of Odd Matrix: -203
Inverse of Even Matrix:
           [,1]       [,2]       [,3]
[1,] -0.2195122  0.2357724  0.2439024
[2,] -0.4146341  0.2601626  0.6829268
[3,]  0.7560976 -0.5528455 -0.9512195

Inverse of Odd Matrix:
            [,1]        [,2]       [,3]
[1,]  0.03940

In [ ]:
sum_of_natural_numbers <- function(n) {
  if (n == 1) {
    return(1)
  } else {
    return(n + sum_of_natural_numbers(n-1))
  }
}
fibonacci <- function(n) {
  if (n <= 2) {
    return(1)
  } else {
    return(fibonacci(n-1) + fibonacci(n-2))
  }
}

print_fibonacci_series <- function(n) {
  for (i in 1:n) {
    cat(fibonacci(i), " ")
  }
  cat("\n")
}
# Find the sum of the first 10 natural numbers
sum <- sum_of_natural_numbers(10)
cat("Sum of first 10 natural numbers:", sum, "\n")

# Print the first 20 Fibonacci numbers
print_fibonacci_series(20)


Sum of first 10 natural numbers: 55 
1  1  2  3  5  8  13  21  34  55  89  144  233  377  610  987  1597  2584  4181  6765  


In [ ]:
# Define the function to partition the data
partition <- function(data, low, high) {
  pivot <- data[high]
  i <- low - 1
  for (j in low:(high - 1)) {
    if (data[j] <= pivot) {
      i <- i + 1
      temp <- data[i]
      data[i] <- data[j]
      data[j] <- temp
    }
  }
  temp <- data[i + 1]
  data[i + 1] <- data[high]
  data[high] <- temp
  return(i + 1)
}

# Define the Quick Sort function
quick_sort <- function(data, low, high) {
  if (low < high) {
    pi <- partition(data, low, high)
    quick_sort(data, low, pi - 1)
    quick_sort(data, pi + 1, high)
  }
}

# Data to be sorted
data <- c(5, 4, 12, 13, 3, 8, 88)

# Sort the data
quick_sort(data, 1, length(data))

# Print the sorted data
cat("Sorted data:", data)


Sorted data: 5 4 12 13 3 8 88